### PR TITLE
Himalaya Migration

### LINKED ISSUE #5: Migration Tool base

### PR DESCRIPTION
**Pull request by pedrovalido**

### CODE REVIEW

**Comment by pedrovalido** [comment]
@DaigaroCota as discussed, I will add tests using foundry to test beginXMigration and receiveXMigration separately as we do it in the router tests.

**Comment by 0xdcota** [comment]
@pedrovalido in this function, after the withdraw action from the V2 market, I think you have to erc20-SafeApprove so that connext address can pull the funds?

https://github.com/Fujicracy/himalaya-migrators/blob/85f836d60402ffabf0735690651d0d6ab96e7bfe/src/migrators/HimalayaCompound.sol#L96-L114

**Comment by 0xdcota** [comment]
@pedrovalido here you have to use the connext domains, not the chain Ids. 
https://github.com/Fujicracy/himalaya-migrators/blob/85f836d60402ffabf0735690651d0d6ab96e7bfe/src/migrators/HimalayaBase.sol#L71-L72

Refer to the domains in the connext [docs](https://docs.connext.network/resources/deployments).
For instance Chain_Id =1 (ethereum mainnet) is Domain_Id = 6648936.

Also you can refer to the connext domains in the FujiV2 test set-up [here](https://github.com/Fujicracy/fuji-v2/blob/d2b86dbddfb12fea8365e35102d498a149edabc3/packages/protocol/test/forking/ChainlinkFeeds.sol#L20-L28).

**Comment by 0xdcota** [comment]
Ignore this message, this is just a test if discord hook update works.

**Comment by 0xdcota** [comment]
@pedrovalido when looking at your code I missed to remember that erc20-asset and erc20-debt have different addresses in the origin and destination chains.

Therefore I propose updating the `Migration` struct:
```solidity
struct Migration {
    address owner;
    address fromMarket;
    address toMarket;
    IERC20 assetOrigin;
    IERC20 assetDest;
    uint256 amount;
    IERC20 debtAssetOrigin;
    IERC20 debtAssetDest;
    uint256 debtAmount;
    uint128 fromChain;
    uint128 toChain;
    address himalaya; //address of himalaya on destination chain
  }
```

Essentially specifying these erc20-addresses in the migration struct, and making them IERC20 type.

**Comment by pedrovalido** [comment]
> @pedrovalido in this function, after the withdraw action from the V2 market, I think you have to erc20-SafeApprove so that connext address can pull the funds?
> 
> https://github.com/Fujicracy/himalaya-migrators/blob/85f836d60402ffabf0735690651d0d6ab96e7bfe/src/migrators/HimalayaCompound.sol#L96-L114

You're right! Implemented the changes. I also missed some approve/send funds between the recently added HimalayaBase and HimalayaCompound

**Comment by pedrovalido** [comment]
@DaigaroCota left some TODO comments so we dont forget to add the borrow, secure router, among others. As discussed, will start a new PR to add the borrow to the migration

**Review by 0xdcota — APPROVED** [review]

**Pull request merged**
